import type { StockLookupOption } from "../types/stockLookup";

export const stockUniverse: StockLookupOption[] = [
  {
    ticker: "AAPL",
    companyName: "Apple Inc.",
    sector: "Technology",
    industry: "Consumer Electronics",
    theme: "Consumer devices and services ecosystem",
  },
  {
    ticker: "MSFT",
    companyName: "Microsoft Corporation",
    sector: "Technology",
    industry: "Software - Infrastructure",
    theme: "Cloud infrastructure and enterprise AI",
  },
  {
    ticker: "NVDA",
    companyName: "NVIDIA Corporation",
    sector: "Technology",
    industry: "Semiconductors",
    theme: "AI accelerators and data center compute",
  },
  {
    ticker: "GOOGL",
    companyName: "Alphabet Inc.",
    sector: "Communication Services",
    industry: "Internet Content and Information",
    theme: "Search, advertising, cloud, and AI platforms",
  },
  {
    ticker: "AMZN",
    companyName: "Amazon.com, Inc.",
    sector: "Consumer Cyclical",
    industry: "Internet Retail",
    theme: "E-commerce, cloud infrastructure, and logistics",
  },
  {
    ticker: "META",
    companyName: "Meta Platforms, Inc.",
    sector: "Communication Services",
    industry: "Internet Content and Information",
    theme: "Social platforms, advertising, and AI engagement",
  },
  {
    ticker: "TSLA",
    companyName: "Tesla, Inc.",
    sector: "Consumer Cyclical",
    industry: "Auto Manufacturers",
    theme: "Electric vehicles, autonomy, and energy storage",
  },
  {
    ticker: "BRK.B",
    companyName: "Berkshire Hathaway Inc.",
    sector: "Financial Services",
    industry: "Insurance - Diversified",
    theme: "Diversified compounder and insurance float",
  },
  {
    ticker: "JPM",
    companyName: "JPMorgan Chase & Co.",
    sector: "Financial Services",
    industry: "Banks - Diversified",
    theme: "Scale banking, payments, and capital markets",
  },
  {
    ticker: "V",
    companyName: "Visa Inc.",
    sector: "Financial Services",
    industry: "Credit Services",
    theme: "Global card network and digital payments",
  },
  {
    ticker: "MA",
    companyName: "Mastercard Incorporated",
    sector: "Financial Services",
    industry: "Credit Services",
    theme: "Global card network and digital payments",
  },
  {
    ticker: "LLY",
    companyName: "Eli Lilly and Company",
    sector: "Healthcare",
    industry: "Drug Manufacturers - General",
    theme: "Diabetes, obesity, and specialty medicines",
  },
  {
    ticker: "UNH",
    companyName: "UnitedHealth Group Incorporated",
    sector: "Healthcare",
    industry: "Healthcare Plans",
    theme: "Managed care and healthcare services",
  },
  {
    ticker: "COST",
    companyName: "Costco Wholesale Corporation",
    sector: "Consumer Defensive",
    industry: "Discount Stores",
    theme: "Membership retail and high-turnover value model",
  },
  {
    ticker: "HD",
    companyName: "The Home Depot, Inc.",
    sector: "Consumer Cyclical",
    industry: "Home Improvement Retail",
    theme: "Home improvement scale retail",
  },
  {
    ticker: "PG",
    companyName: "The Procter & Gamble Company",
    sector: "Consumer Defensive",
    industry: "Household and Personal Products",
    theme: "Global consumer staples brands",
  },
  {
    ticker: "KO",
    companyName: "The Coca-Cola Company",
    sector: "Consumer Defensive",
    industry: "Beverages - Non-Alcoholic",
    theme: "Global beverage brands and distribution",
  },
  {
    ticker: "PEP",
    companyName: "PepsiCo, Inc.",
    sector: "Consumer Defensive",
    industry: "Beverages - Non-Alcoholic",
    theme: "Snacks, beverages, and global distribution",
  },
  {
    ticker: "AVGO",
    companyName: "Broadcom Inc.",
    sector: "Technology",
    industry: "Semiconductors",
    theme: "Networking silicon, infrastructure software, and AI connectivity",
  },
  {
    ticker: "AMD",
    companyName: "Advanced Micro Devices, Inc.",
    sector: "Technology",
    industry: "Semiconductors",
    theme: "CPUs, GPUs, and AI data center compute",
  },
  {
    ticker: "CRM",
    companyName: "Salesforce, Inc.",
    sector: "Technology",
    industry: "Software - Application",
    theme: "Enterprise CRM, automation, and AI software",
  },
  {
    ticker: "ORCL",
    companyName: "Oracle Corporation",
    sector: "Technology",
    industry: "Software - Infrastructure",
    theme: "Enterprise databases, cloud infrastructure, and applications",
  },
  {
    ticker: "NFLX",
    companyName: "Netflix, Inc.",
    sector: "Communication Services",
    industry: "Entertainment",
    theme: "Streaming entertainment and global content platform",
  },
  {
    ticker: "DIS",
    companyName: "The Walt Disney Company",
    sector: "Communication Services",
    industry: "Entertainment",
    theme: "Content franchises, parks, and streaming",
  },
];
